rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
  - jruby-19mode

env:
  - SERIALIZER=YAML
  - SERIALIZER=Marshal
  - SERIALIZER=JSON

services:
  - redis-server

notifications:
  email: true 
